# Generated by Django 4.0.3 on 2022-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("contact_us", models.CharField(max_length=300)),
                ("arrival", models.CharField(max_length=400)),
            ],
        ),
    ]
