# Generated by Django 4.0.3 on 2022-05-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="employee_image/")),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "department_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="team.department",
                    ),
                ),
            ],
        ),
    ]
