# Generated by Django 4.0.3 on 2022-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=300)),
                ("description", models.TextField(max_length=500)),
                ("price", models.IntegerField()),
                ("url_to_photo", models.TextField()),
                ("avaliable", models.BooleanField(default=False)),
            ],
        ),
    ]
