# Generated by Django 4.0.3 on 2022-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_blogpost_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
