# Generated by Django 4.0.3 on 2022-06-07 07:24

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogpost_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=300)),
                ('author', models.TextField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActualNewsArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='None', max_length=300)),
                ('author', models.TextField(default='None', max_length=50)),
                ('text', models.TextField(default='None')),
                ('date', models.DateField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backgrounds', models.FileField(upload_to='backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='collections/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='exposition/')),
                ('title', models.CharField(max_length=155)),
                ('subtitle', models.CharField(max_length=355)),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image_file', models.FileField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('picture', models.ImageField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='ListAudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='picture/')),
                ('inner_picture', models.ImageField(default='default.png', upload_to='picture/inner_pucture')),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='ListVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='picture/')),
                ('inner_picture', models.ImageField(default='default.png', upload_to='picture/inner_pucture')),
                ('description', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='projects/')),
                ('title', models.CharField(max_length=155)),
                ('subtitle', models.CharField(max_length=355)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default="There're no rules at the moment")),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, verbose_name='Name of Ticket')),
                ('text', models.TextField(default="The ticket doesn't have details at the moment")),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=30)),
                ('text', models.TextField(default='Hellp')),
                ('picture', models.ImageField(upload_to='timeline/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('video_file', models.FileField(blank=True, upload_to='video/')),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('description', models.TextField(default='None')),
                ('link_video', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.listvideo')),
            ],
        ),
        migrations.CreateModel(
            name='IntelligentProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='programs/intelligent')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.listvideo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='programs/art')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.listvideo')),
            ],
        ),
        migrations.CreateModel(
            name='AudioDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('video_file', models.FileField(blank=True, upload_to='video/')),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('description', models.TextField(default='None')),
                ('link_audio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.listaudio')),
            ],
        ),
        migrations.CreateModel(
            name='ArtProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='programs/art')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.listvideo')),
            ],
        ),
    ]
