# Generated by Django 4.0.3 on 2022-04-21 15:59

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='picture/')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image_file', models.FileField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('video_file', models.FileField(blank=True, upload_to='video/')),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('link_video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.catalogyvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('link_audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.catalogyaudio')),
            ],
        ),
    ]