# Generated by Django 4.0.3 on 2022-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='catalogyaudio',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='catalogyaudio',
            name='inner_picture',
            field=models.ImageField(default='default.png', upload_to='picture/inner_pucture'),
        ),
        migrations.AddField(
            model_name='catalogyvideo',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='catalogyvideo',
            name='inner_picture',
            field=models.ImageField(default='default.png', upload_to='picture/inner_pucture'),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
