# Generated by Django 4.0.3 on 2022-05-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name of Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ticket_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visit.ticket', verbose_name='which ticket')),
            ],
        ),
    ]
