# Generated by Django 4.0.3 on 2022-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='text',
            field=models.TextField(default="The ticket doesn't have details at the moment"),
        ),
        migrations.DeleteModel(
            name='DetailsTicket',
        ),
    ]
