# Generated by Django 4.0.3 on 2022-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("source_name", models.TextField(max_length=100)),
                ("date", models.DateField()),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
