# Generated by Django 4.0.3 on 2022-05-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligentProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="programs/intelligent")),
                ("title", models.CharField(default="Франко вдома", max_length=55)),
                ("subtitle", models.CharField(default="Блог", max_length=255)),
                (
                    "link_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="multimedia.catalogyvideo",
                        to_field="slug",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="programs/art")),
                ("title", models.CharField(default="Франко вдома", max_length=55)),
                ("subtitle", models.CharField(default="Блог", max_length=255)),
                (
                    "link_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="multimedia.catalogyvideo",
                        to_field="slug",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="programs/art")),
                ("title", models.CharField(default="Франко вдома", max_length=55)),
                ("subtitle", models.CharField(default="Блог", max_length=255)),
                (
                    "link_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="multimedia.catalogyvideo",
                        to_field="slug",
                    ),
                ),
            ],
        ),
    ]
