# Generated by Django 4.0.3 on 2022-05-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0002_audio_description_catalogyaudio_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/intelligent')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.catalogyvideo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/art')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.catalogyvideo')),
            ],
        ),
        migrations.CreateModel(
            name='ArtProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/art')),
                ('title', models.CharField(default='Франко вдома', max_length=55)),
                ('subtitle', models.CharField(default='Блог', max_length=255)),
                ('link_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multimedia.catalogyvideo')),
            ],
        ),
    ]
