# Generated by Django 4.0.3 on 2022-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_partners", models.CharField(max_length=100)),
                ("link_partners", models.URLField(null=True)),
                ("logotype", models.FileField(upload_to="logotype/")),
            ],
        ),
    ]
